name: Pull Request Checks

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build design system
        run: npm run design-system:build

      - name: Generate Prisma client
        run: |
          cd packages/app
          npx prisma generate

      - name: Type checking
        run: npm run type-check

      # Note: ESLint temporarily disabled due to @rushstack/eslint-patch compatibility issue
      # with ESLint 9.x. Type checking, formatting, and tests are still running.
      # - name: Lint code
      #   run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Run tests
        run: npm run test:ci

      - name: Run quality checks (without linting)
        run: npm run quality:no-lint

      - name: Build application
        env:
          NEXTAUTH_SECRET: dummy-secret-for-build
        run: |
          cd packages/app
          NODE_ENV=production npm run build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: success()
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Check for vulnerabilities
        run: npm audit --audit-level=high --production
